export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const SETUP_USER_ERROR = "SETUP_USER_ERROR"

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const LOGOUT_USER = "LOGOUT_USER"

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const SELECTED_MOVIE = "SELECTED_MOVIE"
export const REMOVE_MOVIE = "REMOVE_MOVIE"
export const SUBMIT_REVIEW = "SUBMIT_REVIEW"

export const HANDLE_MOVIE_CHANGE = "HANDLE_MOVIE_CHANGE"

export const CREATE_MOVIE_BEGIN = "CREATE_MOVIE_BEGIN"
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS"
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR"
